version: "3.8"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "8081:8081"
    environment:
      - USER_SERVICE_SERVER_PORT=8081
      - USER_SERVICE_DATABASE_URL=postgres://user:pass@postgres:5432/shopstream?sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=shopstream
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d shopstream"]
      interval: 10s
      timeout: 5s
      retries: 5
